import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import ScrollReveal from "@/components/ScrollReveal";
import Analytics from "@/components/Analytics";
import JsonLd from "@/components/JsonLd";
import {
  SITE_URL,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_DESCRIPTION,
  SITE_KEYWORDS,
} from "@/lib/site";
import "./globals.css";

// GitLab Sans (Inter-based) — the Pajamas design system UI face, self-hosted
// variable file from @gitlab/fonts.
const gitlabSans = localFont({
  src: "./fonts/GitLabSans.woff2",
  weight: "100 900",
  display: "swap",
  variable: "--font-gitlab-sans",
  adjustFontFallback: false,
});

// GitLab Mono (JetBrains Mono-based) — data voice: prices, hashes, counters.
const gitlabMono = localFont({
  src: "./fonts/GitLabMono.woff2",
  weight: "100 900",
  display: "swap",
  variable: "--font-gitlab-mono",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  // metadataBase lets every relative OG/canonical URL below resolve to an
  // absolute one, and points social/AI crawlers at the right origin.
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} - ${SITE_TAGLINE}`,
    // Child routes set a bare title (e.g. "API") and inherit the suffix.
    template: `%s - ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: SITE_KEYWORDS,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "technology",
  // Home is the canonical for "/"; child routes override with their own path.
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: `${SITE_NAME} - ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    // OG image is generated by app/opengraph-image.tsx and inherited here.
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} - ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // Let Google show full-size render previews and untruncated snippets.
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: { telephone: false },
  icons: {
    icon: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#171321" },
  ],
};

// Sitewide structured data: who Farpy is (Organization) and the site itself
// (WebSite). Emitted once in the root layout so it appears on every page —
// the anchor that lets Google and AI engines attribute facts to the brand.
const orgId = `${SITE_URL}/#organization`;
const siteLd = [
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": orgId,
    name: SITE_NAME,
    url: SITE_URL,
    description: SITE_DESCRIPTION,
    // `logo` intentionally omitted until the real brand logo lands — add a
    // square PNG (e.g. /icon.png) here then for knowledge-panel / rich results.
    sameAs: [] as string[],
  },
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    name: SITE_NAME,
    url: SITE_URL,
    description: SITE_DESCRIPTION,
    publisher: { "@id": orgId },
    inLanguage: "en",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gitlabSans.variable} ${gitlabMono.variable}`}
      suppressHydrationWarning
    >
      <body>
        {/* No-flash boot: hide [data-reveal] before first paint, but only when
            motion is welcome and we can observe scroll. Absent this class,
            reveals never apply and content shows normally. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('reveals-on')}}catch(e){}",
          }}
        />
        {children}
        <ScrollReveal />
        <Analytics />
        <JsonLd data={siteLd} />
      </body>
    </html>
  );
}
